env: app
vpc_cidr: 10.2.0.0/16
vpc_name: app-vpc

subnets:
- name: app-elb-subnet
  public: "True"
  cidr: 10.2.1.0/24
  zone: ap-southeast-2a
- name: app-bastion-subnet
  public: "True"
  cidr: 10.2.2.0/24
  zone: ap-southeast-2a
- name: app-web-subnet
  public: "False"
  cidr: 10.2.11.0/24
  zone: ap-southeast-2a

security_groups:
- name: app-elb-sg
  rules:
  - cidr: 0.0.0.0/32
    ports:
    - 80
    - 443
    proto: tcp
- name: app-bastion-sg
  rules:
  - cidr: 0.0.0.0/32
    ports: 22
    proto: tcp
- name: app-web-sg
  rules:
  - group_name: app-bastion-sg
    ports: 22
    proto: tcp
  - group_name: app-elb-sg
    ports: 8080
    proto: tcp
