cidr: 10.1.0.0/16
name: ci-vpc

subnets:
- name: ci-jenkins-elb-subnet
  public: "True"
  cidr: 10.1.1.0/24
  zone: ap-southeast-2a
- name: ci-bastion-subnet
  public: "True"
  cidr: 10.1.2.0/24
  zone: ap-southeast-2a
- name: ci-jenkins-web-subnet
  public: "False"
  cidr: 10.1.11.0/24
  zone: ap-southeast-2a
- name: ci-jenkins-agent-subnet
  public: "False"
  cidr: 10.1.21.0/24
  zone: ap-southeast-2a

security_groups:
- name: ci-jenkins-elb-sg
  rules:
  - cidr_ip: 0.0.0.0/0
    ports:
    - 80
    - 443
    proto: tcp
- name: ci-bastion-sg
  rules:
  - cidr_ip: 0.0.0.0/0
    ports: 22
    proto: tcp
- name: ci-jenkins-web-sg
  rules:
  - group_name: ci-bastion-sg
    ports: 22
    proto: tcp
  - group_name: ci-jenkins-elb-sg
    ports: 8080
    proto: tcp
- name: ci-jenkins-agent-sg
  rules:
  - group_name: ci-jenkins-web-sg
    ports: 5000
    proto: tcp

load_balancers:
- name: ci-jenkins-elb
  zones:
  - ap-southeast-2a
  listeners:
  - protocol: http
    load_balancer_port: 80
    instance_port: 8080
  tags:
    Application: jenkins
