- name: determine ec2_instance subnet id
  ec2_vpc_subnet_facts:
    filters:
      tag:Name: "{{ ec2_instance_subnet }}"
    profile: "{{ profile|default(omit) }}"
    region: "{{ region }}"
  register: ec2_instance_subnet_fact

- name: upload keypair
  ec2_key:
    name: "{{ ec2_instance_key_name }}"
    key_material: "{{ item }}"
    profile: "{{ profile|default(omit) }}"
    region: "{{ region }}"
  with_file: "{{ ec2_instance_ssh_public_key_file }}"

- name: create ec2_instance instance
  ec2:
    instance_type: "{{ ec2_instance_size }}"
    key_name: "{{ ec2_instance_key_name }}"
    instance_tags:
      Application: ec2_instance
      Environment: "{{ env }}"
    vpc_subnet_id: "{{ ec2_instance_subnet_fact.subnets[0].id }}"
    group: "{{ ec2_instance_sg }}"
    profile: "{{ profile|default(omit) }}"
    region: "{{ region }}"
    image: "{{ ec2_instance_image }}"
    assign_public_ip: "{{ ec2_instance_public_ip }}"
    wait: yes
    wait_timeout: 300
