- hosts: ci-jenkins-web-runner

  roles:
  - ec2_instance

- hosts: localhost

  tasks:
  - meta: refresh_inventory

- hosts: tag_Application_jenkins_web
  connection: local

  roles:
  - jenkins-setup

- hosts: tag_Application_jenkins_web
  become: True

  roles:
  - geerlingguy.jenkins
